---
# file: roles/common/tasks/main.yml

- name: mount / with inode_readahead_blks=128,noatime,commit=30,errors=remount-ro
  shell: creates=/etc/fstab.bak chdir=/etc cp fstab fstab.bak && sed -i "s/ errors=remount-ro/ inode_readahead_blks=128,noatime,commit=30,errors=remount-ro/" fstab
  tags: slaves

- name: install commonly used packages via yum
  yum: name={{ item }} state=installed
  with_items:
    - curl
    - wget
    - lzo-devel
    - ntp
    - rsyslog
    - libselinux-python
  tags:
    - ntp
    - slaves

- name: configure /etc/security/limits.conf with high max file descriptors (soft/hard)
  template: src=limits.conf dest=/etc/security/limits.conf mode=0644
  tags: slaves

- name: create the hosts file for all machines
  template: backup=yes src=hosts dest=/etc/hosts
  tags:
    - slaves

- name: configure rsyslog with the imfile module
  template: src=rsyslog.conf dest=/etc/rsyslog.d/30-imfile.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog

- name: configure NTP in /etc/ntp.conf
  template: src=ntp.conf dest=/etc/ntp/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: make sure NTP is enabled and started
  service: name=ntpd enabled=yes state=started
  tags: ntp

- name: update iptables
  template: backup=yes src=iptable dest=/etc/sysconfig/iptables
  tags: slaves
  notify: restart iptables

- name: remove OpenJDK
  yum: name={{ item }} state=removed
  with_items: 
   - java
   - jdk
  tags: slaves

- name: copy Sun JDK package
  copy: src=dependencies/jdk-7u67-linux-x64.rpm dest=/tmp/jdk-7u67-linux-x64.rpm
  tags: slaves

- name: install the Sun JDK package
  command: rpm -Uvh /tmp/jdk-7u67-linux-x64.rpm
  tags: slaves

- name: disable SELinux in conf file
  lineinfile: dest=/etc/sysconfig/selinux regexp='^SELINUX=' line='SELINUX=disabled' state=present
  tags: slaves

- name: disable SELinux dynamically
  shell: creates=/etc/sysconfig/selinux.disabled setenforce 0 ; touch /etc/sysconfig/selinux.disabled
  tags: slaves

